# Generated by Django 5.0.7 on 2024-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='address',
            name='postalcode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
